# Generated by Django 5.2.1 on 2025-05-30 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('jobs', '0001_initial'),
        ('workers', '0002_workerskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.workerprofile'),
        ),
        migrations.AddField(
            model_name='assignmentcheckin',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentcheckin',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.workerprofile'),
        ),
        migrations.AddField(
            model_name='assignmentmilestone',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
    ]
